  services:
    web:
      image: abhaypande/flask-jenkins
      build: .
      ports:
        - "8000:8000"
      deploy:
        replicas: 1    
    redis:
      image: redis:alpine
      deploy:
        replicas: 1
